const Products = [
    {
      id: 1,
      name: "Product 1",
      productCategory: "Comfort in a bag",
      description: "Description 1 asdsada asdsada dasdsad asdasd sa asda d",
      price: "29.99",
      image: "/images/home/newarrivels/c1.png",
      categories: ["new"],
    },
    {
      id: 2,
      name: "Product 2",
      productCategory: "Comfort in a bag",
      description: "Description 2",
      price: "39.99",
      image: "/images/home/newarrivels/c2.jpg",
      categories: ["new", "featured"],
    },
    {
      id: 3,
      name: "Product 3",
      productCategory: "Comfort in a bag",
      description: "Description 3",
      price: "49.99",
      image: "/images/home/newarrivels/c3.jpg",
      categories: ["new", "top-rated"],
    },
    {
      id: 4,
      name: "Product 4",
      productCategory: "Comfort in a bag",
      description: "Description 4",
      price: "59.99",
      image: "/images/home/newarrivels/c4.jpg",
      categories: ["new"],
    },
    {
      id: 5,
      name: "Product 5",
      productCategory: "Comfort in a bag",
      description: "Description 5",
      price: "69.99",
      image: "/images/home/newarrivels/c5.png",
      categories: ["featured"],
    },
    {
      id: 6,
      name: "Product 6",
      productCategory: "Comfort in a bag",
      description: "Description 6",
      price: "79.99",
      image: "/images/home/newarrivels/c6.png",
      categories: ["featured", "top-rated"],
    },
    {
      id: 7,
      name: "Product 7",
      productCategory: "Comfort in a bag",
      description: "Description 7",
      price: "89.99",
      image: "/images/home/newarrivels/c7.png",
      categories: ["featured"],
    },
    {
      id: 8,
      name: "Product 8",
      productCategory: "Comfort in a bag",
      description: "Description 8",
      price: "99.99",
      image: "/images/home/newarrivels/c8.jpg",
      categories: ["featured"],
    },
    {
      id: 9,
      name: "Product 9",
      productCategory: "Comfort in a bag",
      description: "Description 9",
      price: "109.99",
      image: "/images/home/newarrivels/c2.jpg",
      categories: ["top-rated"],
    },
    {
      id: 10,
      name: "Product 10",
      productCategory: "Comfort in a bag",
      description: "Description 10",
      price: "119.99",
      image: "/images/home/newarrivels/c3.jpg",
      categories: ["top-rated"],
    },
    {
      id: 11,
      name: "Product 11",
      productCategory: "Comfort in a bag",
      description: "Description 11",
      price: "129.99",
      image: "/images/home/newarrivels/c4.jpg",
      categories: ["top-rated"],
    },
    {
      id: 12,
      name: "Product 12",
      productCategory: "Comfort in a bag",
      description: "Description 12",
      price: "139.99",
      image: "/images/home/newarrivels/c8.jpg",
      categories: ["top-rated"],
    },
  ];

export default Products;